# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - whoami.md
  - mesg.md

footer: 'Follow me on <a href="https://www.instagram.com/chunhaoxx/">Instagram</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

permalink: pretty
